### ISSUE TITLE
Proposal: support operation callback

### ISSUE THREAD

**Issue by ipfans** [Fs02/rel#29]
As #28 , callback functions could be used to enhance logging or trace execution times (with opentracing etc).

**Comment by Fs02** [comment]
Hi, I just want to make sure that I understand you right. what do you mean but operation callback is the callback that applies to globally to the `Repository` object right? not the one that applies on model? 

If yes, there's a very basic callback for logging right now: https://github.com/Fs02/rel/blob/master/repository.go#L47-L49
But I think we can do better in that regard to better facilitate instrumentation. If you have any idea, let me know :)
