### ISSUE TITLE
The name of savepoint may conflict in multi process env

### ISSUE THREAD

**Issue by heww** [Fs02/rel#30]
Suggest to use a random prefix for the savepoint name.

https://github.com/Fs02/rel/blob/master/adapter/sql/adapter.go#L169

**Comment by Fs02** [comment]
Hi @heww, Thank you very much for the suggestion and your time to look at the code 😄 

From what I know, savepoint name is distinct within current transaction, at least that's what stated explicitly in oracle [documentation](https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_10001.htm).
Even activerecord also uses increment number to identify its save point: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb#L223 

I haven't encounter such a problem in production so far, If you did, could you maybe make a simple program to reproduce it?

Thanks

**Comment by heww** [comment]
En, you are right, it's my mistake.
