### ISSUE TITLE
Log queries ?

### ISSUE THREAD

**Issue by Vahanerevan** [Fs02/rel#43]
Hi , Thanks for this perfect tool , sure it will get many stars soon.
Is there any way to use the logger or add custom logging ...? 
Thank you.

**Comment by Fs02** [comment]
Hi, Thank you.

Yes, you can implement your own instrumenter, and apply it using `repo.Instrumenter(instrumenterFunction)`.

it's currently shipped with DefaultLogger as instrumenter (https://github.com/Fs02/rel/blob/22baaec327dce5a5476d813970d1e08159b1fe7c/instrumentation.go#L14-L25).

**Comment by Fs02** [comment]
I'm closing this issue for now, if you have further questions, suggestions or ideas, please let me know! thanks
