### ISSUE TITLE
Cascade delete support?

### ISSUE THREAD

**Issue by fr3fou** [Fs02/rel#47]
hi!

just found your project on reddit and I'm very interested in trying it out. i've used gorm before but couldn't get myself to like it, this seems like a viable alternative.

as for my question, does rel support cascade delete as of this point?

**Comment by Fs02** [comment]
Hi, what kind of cascade delete? do you have reference on what other libraries does?

I think, cascade delete is better to be delegated to database or maybe handled manually.

**Comment by Fs02** [comment]
I'm closing this issue for now, if you have further questions, suggestions or ideas, please let me know! thanks

**Comment by Fs02** [comment]
Hi, I'm opening this issue again, as I might know what you meant by cascade delete.

As for know, rel supports creating or updating it's association. When updating, rel will only updates any association that's already loaded.

I think it's fair to give delete the same behavior, It should also delete any association that's already loaded, what do you think?

**Comment by fr3fou** [comment]
> I think it's fair to give delete the same behavior, It should also delete any association that's already loaded, what do you think?

yea + have some API to enable / disable that

**Comment by Fs02** [comment]
hmm, before we can delete any association, first they need to preload the association first, isn't that explicit enough?

I actually don't know what kind of API is good for this case if we need to add one

**Comment by Fs02** [comment]
I have an idea for an API to enable/disable that.
It'll be an option called `Cascade` which can be used on `Delete` and `Update`/`Insert`.
- `Update`/`Insert`: default true, when enabled, It'll also updates/creates its associations, disabling this will allow users to only update the main struct (for example when they are sure there's no updates on the association and want to skip the updating process when using Structset mutators).
- `Delete`: default false, when enabled, It'll also deletes it's associations.

Cascade will implement `Mutator` interface so it can be passed as one of mutators arguments. and also implements a new interface (name tbd) used only by Delete.

**Comment by fr3fou** [comment]
That sounds great! I'm very excited to see this project grow!

**Comment by Fs02** [comment]
Rel supports application level cascade delete now! Thanks
