### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by fr3fou** [Fs02/rel#48]
How can I check what type of error was returned?
Using `database/sql` or anything similar I could simply do:
```go
err := ...
switch {
	errors.Is(err, db.ErrNoMoreRows):
		// handle for ErrNoMoreRows
	errors.Is(err, db.ErrForeignKeyConstraint): // psuedo error, doesn't actually exist
		// handle for ErrForeignKeyConstraint
	default:
		// handle default
}
```
How can I apply the same pattern here?

**Comment by Fs02** [comment]
Hi, that patterns looks interesting. Will need some works to make it happen.

As so far, rel have two kind of [error struct,](https://github.com/Fs02/rel/blob/master/errors.go) NoResultError and ConstraintError. If you want to handle using switch, it may look like this:

```golang
switch v := err.(type) {
    case rel.NotFoundError:
        // handle not found
    case rel.ConstraintError:
        switch v.Type {
            rel.CheckConstraint:
                // handle
            rel.NotNullConstraint:
                // handle
            rel.UniqueConstraint:
                // handle
            rel.PrimaryKeyConstraint:
                // handle
            rel.ForeignKeyConstraint:
                // handle
        }
    default:
        // handle default
}
```

**Comment by Fs02** [comment]
error handling using `errors.Is` is now supported, thanks for the suggestion 💯
