### ISSUE TITLE
Has this project card been resolved?

### ISSUE THREAD

**Issue by fr3fou** [Fs02/rel#78]
https://github.com/Fs02/rel/projects/1#card-36127998

I wanted to contribute to `rel` by solving that issue but after cloning and examining the project, I noticed that the `Adapter` struct already has an exported `DB` field, making a `DB()` getter useless. What should I do regarding that?

**Comment by Fs02** [comment]
Not yet, feel free to work on that 👍

**Comment by fr3fou** [comment]
What should I do if it's basically done though? (a field already exists with the same name)

**Comment by Fs02** [comment]
Hmm, right, Sorry I forgot that is already there as exported variable and works 🙈
I'll delete that card
