### ISSUE TITLE
Non-magical structset

### ISSUE THREAD

**Issue by skolodyazhnyy** [Fs02/rel#81]
Hey,

Great library, very nice and clean. One thing I find a bit inconvenient is default Structset mutator, which treats `primary`, `created_at`, `inserted_at` and `updated_at` fields differently. I would like to explicitly set `created_at` field when I'm creating record as well as `updated_at` when I'm updating it, it's not that much code really but gives you full control on how things are executed. Also, I would like to manually generate UUID (primary key) for a record before inserting it, but default `Structset` mutation does not allow to insert primary key, it simply excludes it (I assume because it expects database to generate primary key using auto-increment or something).

It would be great to have "non-magical" version of Structset which would insert/update data as is without any assumptions.

For the moment as workaround I use combination of `Structset` and `Set` mutators:

```go
orm.Insert(ctx, record, rel.NewStructset(record, false), rel.Set("id", record.ID))
```

A bit verbose but does the job.

**Comment by Fs02** [comment]
Hi, Thank you for trying REL.

A manually generated primary key is something that REL want to support, I think we can [fix](https://github.com/Fs02/rel/projects/1#card-42213874) it by allowing primary field to be explicitly set as long as it's not a zero value.

With current implementation, It should be possible to specify `created_at` explicitly, but not `updated_at`. I'll have to think about this for a bit, there's 3 possible options to choose:

- Introduce a new argument to `NewStructset` to allow skipping timestamp update.
- Create a new mutator for this, maybe we can call it `Dump`? (need a better name).
- Split NewStructset behaviour to have timestamp updated in a separated Timestamp mutator, and by default repository will use that both.

**Comment by skolodyazhnyy** [comment]
Hey,

Regarding `id`, I think it's a good option. If it's a primary key there is no use case for an empty value except when we want database to generate it. Sounds good, let me PR 😄 

For `created_at` and `updated_at`, maybe separate mutator would do the job.

**Comment by Fs02** [comment]
Hi,

Thank you, looking forward for your PR 😄

Yes, looks like I'll go with having [separate mutator](https://github.com/Fs02/rel/projects/1#card-42354033) for setting timestamp.

**Comment by skolodyazhnyy** [comment]
I think we can close this task because primary key changes are implemented and there is task for separate mutator for timestamp already. Although feel free to reopen if needed.

**Comment by Fs02** [comment]
Hi,

I'm wondering if you have already encontered a problem when updating a record with has many association, caused by this line?
https://github.com/Fs02/rel/blob/438726cbb3a91799ed40b7860bd9660bb0f6953c/structset.go#L118

**Comment by Fs02** [comment]
Update: should be fixed with this PR: https://github.com/Fs02/rel/pull/87
