### ISSUE TITLE
Cascading does not work when updating an entity without changes

### ISSUE THREAD

**Issue by skolodyazhnyy** [Fs02/rel#85]
Hey, 

I'm having some troubles cascading updates using rel. I have a database entity with one-to-many relation:

```go
type User struct {
    ID string
    Name string
    Score []Score
    TotalScore int
}

type Score struct {
    ID string
    Name string
    Value int
}
```

What I'm trying to do is to update user's `Score` field, as well as `TotalScore` field. The code looks something like this:

```go
user.Scores = scores
user.TotalScore = total

repo.Update(ctx, user, rel.Cascade(true))
```

This works sometimes 😅  

What happens is, if `TotalScore` has changed User entity will be updated and Scores updates will be cascaded too. But, if `TotalScore` value has not changed, the transaction gets rolled back and Scores never updated. It happens due to [updatedCount check in repository.go](https://github.com/Fs02/rel/blob/438726cbb3a91799ed40b7860bd9660bb0f6953c/repository.go#L410):

```go
	if !mutation.IsMutatesEmpty() {
		var (
			query = r.withDefaultScope(doc.data, Build(doc.Table(), filter, mutation.Unscoped))
		)

		if updatedCount, err := cw.adapter.Update(cw.ctx, query, mutation.Mutates); err != nil {
			return mutation.ErrorFunc.transform(err)
		} else if updatedCount == 0 {
			return NotFoundError{}  // RETURNS HERE
		}

		if mutation.Reload {
			if err := r.find(cw, doc, query); err != nil {
				return err
			}
		}
	}

	if mutation.Cascade { // NEVER REACHED
		if err := r.saveHasOne(cw, doc, &mutation); err != nil {
			return err
		}

		if err := r.saveHasMany(cw, doc, &mutation, false); err != nil {
			return err
		}
	}
```

Repository returns an error when entity hasn't change, so cascading is not happening.

As a workaround I've added `updated_at` field which creates "fake" change in User entity always. But I think rel should be propagating changes even if "root" entity didn't change. In general, I'm not sure if it's "error" situation when update was no-op.

**Comment by Fs02** [comment]
Hi,

I tried to reproduce with this code, but it works without problem: https://github.com/Fs02/rel/commit/45d2ab42b1bc88925a9ff733c83323d4898c9c73

Are you reusing some MySQL connection? If that the case, you need to specify `clientFoundRows=true` options.
https://github.com/Fs02/rel/blob/438726cbb3a91799ed40b7860bd9660bb0f6953c/adapter/mysql/mysql.go#L50-L52

**Comment by skolodyazhnyy** [comment]
Got it! I was re-using MySQL connection without `clientFoundRows=true` set.
